### ISSUE TITLE
Code does not work at all

### ISSUE THREAD

**Issue by ldionmarcil** [huntergregal/PNG-IDAT-Payload-Generator#3] opened 2017-01-18 09:07 UTC
Has this ever been tested at all? There is no way this can even function.

```
def generateFinalPayload(payload, outputImage):
	print "[+] Generating final PNG payload..."
	#Thanks to admanLogue and hLk_886 for this PNG Code
	im = Image.new('RGB', (32,32))
	i = 0
	c = 0
	if i >= len(payload):
		r = payload[i]
		g = payload[i+1]
		b = payload[i+2]
		im.putpixel((c,0), (r,g,b))
		i += 3
		c += 1
```

The `if` here will never be true! And even if it were true, im.putpixel() will ultimately fail because r,g and b are bytes (in string) and putpixel expects integers. 

This was not tested at all and cannot work!

**Comment by ldionmarcil** [comment] 2017-01-18 09:24
I've just read the last commits. Do you need help with debugging the application or have you got more time on your hands lately?

**Comment by huntergregal** [comment] 2017-01-19 21:20
yes it does not work. i explained that when i put in the readme that it does not work. it's a half port from someone else's code. no i still do not have time to debug it. i am working on a big private repo project right now. feel free to have at it

**Comment by huntergregal** [comment] 2017-01-20 20:30
The problem is in the filter payload generation. - in fact i can not get any of the coode or payloads from the referenced material to work. I even copied the php code from i dont play with darts and their payload and cannot generate the proper array by reversing filter 1 and 3 as described. 

I can generate the reverse of filter 1, but filter 3's algorithim appears wrong

**Comment by huntergregal** [comment] 2017-01-20 20:58
in fact, after the filter 3 payload there are 3 extra bytes that seem to come from no where. 0x44,0x50,0x33

Some information is being ommited

**Comment by ldionmarcil** [comment] 2017-01-20 21:14
I agree the original post does leave out a lot of information. I'm trying to reproduce it locally right now. Will update.

**Comment by ldionmarcil** [comment] 2017-01-20 21:26
I figured it out. For filter 1, you have to go through the same algorithm but disregard the `bList2[i+3]` for the last three iterations, considering this will return nothing (index out of bound). See this:

```
(Pdb) hex(floor(bList2[i] / 2) % 256)
'0x44'
(Pdb) hex(floor(bList2[i+1] / 2) % 256)
'0x50'
(Pdb) hex(floor(bList2[i+2] / 2) % 256)
'0x33'
```

**Comment by huntergregal** [comment] 2017-01-20 21:36
that's a big thing to leave out. additionally I have been able to generate the payload in PHP by cutting off those last 3 bytes anyway. 

The issue appears that the function for filter 3 in python is producing different results than in php:

assume bList2 = hex list of "a39f67546f2c24152b116712546f112e29152b2167226b6f5f5310"

python:
```
i=0
while i<(len(bList2)-3):
   bList2[i+3] = (bList2[i+3] + int(bList2[i] / 2)) % 256
   i+=1
for filter3 in bList2:
    payload.append(filter3)
print payload
```
PHP:
```
for ($i=0; $i<sizeof($bList2)-3; $i++){
   $bList2[$i+3] = ($bList2[$i+3] + floor($bList2[$i]) / 2)) % 256;
}
var_dump($bList2);
```

**Comment by huntergregal** [comment] 2017-01-20 21:37
fixing this filter 3 issue may fix the the png generation - as starting payloads are successfully being brute forced

**Comment by ldionmarcil** [comment] 2017-01-20 21:50
Filter 1 is also broken, the last 3 bytes need to be repeated. I think adding `payload.extend(payload[-3:])` after the reverse-filter would fix this.

**Comment by huntergregal** [comment] 2017-01-20 21:53
The last 3 bytes shouldn't need to be repeated - where did you find that?  filter 1 on the payload should result in - 0xa3, 0x9f, 0x67, 0xf7, 0xe, 0x93, 0x1b, 0x23, 0xbe, 0x2c, 0x8a, 0xd0, 0x80, 0xf9, 0xe1, 0xae, 0x22, 0xf6, 0xd9, 0x43, 0x5d, 0xfb, 0xae, 0xcc, 0x5a, 0x1, 0xdc, 0x5a, 0x1, 0xdc, 

Which is currently working for me. and i have generated a valid png from this with filter3 in php.

filter 3 in python is failing though.

**Comment by ldionmarcil** [comment] 2017-01-20 21:57
Does this work for you?

```
i = 0
bList_length = len(bList2)
while i < bList_length:
    if (len(bList2)-i) > 3:
        bList2[i+3] = (bList2[i+3] + floor(bList2[i] / 2)) % 256
    else:
        bList2.append((floor(bList2[i] / 2)) % 256)
    i += 1

for filter3 in bList2:
    payload.append(int(filter3))
```

**Comment by huntergregal** [comment] 2017-01-25 19:46
This looks good and results in no errors - but is still not returning the same results idontplaywithdarts got despite using the same starting payload:

a39f67485dc63f51214bb2e0a55251004b1ed9686c67e2028d72dd46396e is the result of your code.

But if you run test.php you can see the second part of the array (which holds filter 3 after XXXX), the results do not match.

The desired result: 0xa3, 0x9f, 0x67, 0xa5, 0xbe, 0x5f, 0x76, 0x74, 0x5a, 0x4c, 0xa1, 0x3f, 0x7a, 0xbf, 0x30, 0x6b, 0x88, 0x2d, 0x60, 0x65, 0x7d, 0x52, 0x9d, 0xad, 0x88, 0xa1, 0x66, (different format but you get the point)

**Comment by huntergregal** [comment] 2017-01-25 19:51
It might honestly be worth scrapping the payloads in all the blogs and basically reversing this ourselves. I'm disappointed in the blogs that report on this. There was another code that I reference in my readme.md that was hosted on github that has also since been removed. I'm not sure what the secrecy is about here.

**Comment by TheZ3ro** [comment] 2019-09-17 20:03
Hi, 
I've fixed the bug with filter3, implemented multithread bruteforcing, cleaned the code and made it Python3 ready.
Also I've removed extra file from the repository.

the commit/repo is here: https://github.com/TheZ3ro/PNG-IDAT-Payload-Generator/commit/9b53782d18a3b4abab6c8ab47264c61279679641

**Comment by huntergregal** [comment] 2019-09-17 20:09
ayy i just started reworking on this last night - what are the odds. Nice work.

**Comment by huntergregal** [comment] 2019-09-17 20:16
closing thanks to TheZ3ro

**Closed as completed by huntergregal** 2019-09-17 20:16 UTC
